### ISSUE TITLE
Bitrise

### ISSUE THREAD

**Issue by trigodetRobin** [cookpad/dokumi#17]
Hello, 

first of all, i need to salute your work, it's seems really nice. 

My question is, do you plane to work on bitrise integration for dokumi ?

**Comment by vincentisambart** [comment]
Hello,
Sorry for the late reply.
No, no no bitrise integration planned.
In fact we've been moving our projects from using Dokumi to using fastlane + danger instead so we're probably not going to add any new features to Dokumi.
Cheers
